format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/1.1/restricted/ukmo/release/linux-x86_64_v4/um7-git.2026.02.000_access-esm1.6-7cmpnxlr3viabrqh3urxtam72pdhsnnk/bin/um_hg3.exe
  hashes:
    binhash: 24441fb363225ea9aa36ccf469407271
    md5: a4a5cc3bc4d3ae582d27d0d813945d36
