format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/1.1/restricted/ukmo/release/linux-x86_64_v4/um7-2026.04.002-pwcjur4jpkft64z3fxr2v5nmtqszbvur/bin/um_hg3.exe
  hashes:
    binhash: 9701c6ea6e4c4314915119772f87cab1
    md5: 8a39f3b963c0ad72150eedb7fa012970
