format: yamanifest
version: 1.0
---
work/atmosphere/INPUT/ACCESS_vegfrac_LUH3_states_withAusPFTs_1850-2023_v7-transposed.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/land/vegetation/global.N96/2025.11.25/ACCESS_vegfrac_LUH3_states_withAusPFTs_1850-2023_v7-transposed.nc
  hashes:
    binhash: 47e5d30c68d865d0037a760f37f46ad5
    md5: 91e2f9f2ac9e7e6ed308cd414ee78ef2
work/atmosphere/INPUT/BC_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/aerosol/global.N96/2026.01.06/BC_1849_2023_cmip7.anc
  hashes:
    binhash: c5ce9bdbd5bc7a53495fb06ccbbd5bd6
    md5: 1f5905bdfcbda0c0611759edc3bc6eff
work/atmosphere/INPUT/Bio_1849_2015_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/Bio_1849_2015_ESM1.anc
  hashes:
    binhash: 3d1bbeea23f49ee75e7cc9c0f41c9db5
    md5: fb650ff10a39596b92f67b1393c15289
work/atmosphere/INPUT/Bio_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/aerosol/global.N96/2026.01.06/Bio_1849_2023_cmip7.anc
  hashes:
    binhash: f500982a87f69247c3272281d8b87d79
    md5: 4833f61b70851198aacb73ab3297a846
work/atmosphere/INPUT/DMS_conc.N96:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/DMS_conc.N96
  hashes:
    binhash: da1baa25e78ec281c82ea4588e30a340
    md5: 7e8ec8de832c0b9b8c1d9f0eda4d54e5
work/atmosphere/INPUT/LUH3_cable_thinning_frac_from_bioh_1850-2023_v2.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/land/vegetation/global.N96/2026.05.08/LUH3_cable_thinning_frac_from_bioh_1850-2023_v2.nc
  hashes:
    binhash: f1fdb2086513600bebfc3fb1ff18293e
    md5: 4fe37dc3a0222f63f657ae5dad9643a7
work/atmosphere/INPUT/Ndep_1849_2023_cmip7_v2_0.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/land/biogeochemistry/global.N96/2026.03.27/Ndep_1849_2023_cmip7_v2_0.anc
  hashes:
    binhash: 8246c7eb1a6b57994cf0c6e940714c75
    md5: 6e52abfc4ebea29d0ae8fdfd241df406
work/atmosphere/INPUT/OCFF_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/aerosol/global.N96/2026.01.06/OCFF_1849_2023_cmip7.anc
  hashes:
    binhash: 449b218265a03566458459ff0e5758cd
    md5: 04394cfbeba09f463929406065fb5d14
work/atmosphere/INPUT/STASHmaster/README:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/README
  hashes:
    binhash: b83a0a9996df33aa034983d989696061
    md5: 68d47be694979b827a9f68088d8d5800
work/atmosphere/INPUT/STASHmaster/STASHmaster_A:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHmaster_A
  hashes:
    binhash: 5cb00fc6f6d0a235522ab8cd8176e340
    md5: 808dac1f259bf3e3fb468462ccbbee81
work/atmosphere/INPUT/STASHmaster/STASHmaster_O:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHmaster_O
  hashes:
    binhash: 19606c7f321baddeed74d3ae7a2d7fd6
    md5: 5a65d77c62d55e3b62e35ad9662d32a9
work/atmosphere/INPUT/STASHmaster/STASHmaster_S:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHmaster_S
  hashes:
    binhash: 17313250832ceddf9d771766b925ec7f
    md5: 85ff5d563968cf24d1be595b05b4e52d
work/atmosphere/INPUT/STASHmaster/STASHmaster_W:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHmaster_W
  hashes:
    binhash: 7d0f5c2837a4570522cf6cc5c94a02fe
    md5: 1e4391ea1f6234b33c33168bd7089d06
work/atmosphere/INPUT/STASHmaster/STASHsections_A:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHsections_A
  hashes:
    binhash: 7cf9456d4d36eafd1ace4e9f127c91b6
    md5: 8525fd107dbea6184db74089f1d55fd9
work/atmosphere/INPUT/TSI_CMIP7_ESM:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/forcing/resolution_independent/2025.11.25/TSI_CMIP7_ESM
  hashes:
    binhash: 6aa7e61e4ae674e1782dda9046f4331e
    md5: 635295693e07ae1079753d0835a6ad07
work/atmosphere/INPUT/amip_seaice_n96_greg.pp:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p5/modern/amip/atmosphere/boundary_conditions/global.N96/2021.07.08/amip_seaice_n96_greg.pp
  hashes:
    binhash: 81345cbc844a887e5eea04687dcc1e1c
    md5: dee51bc6417e99297d70e557ac52632a
work/atmosphere/INPUT/amip_sst_n96_greg.pp:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p5/modern/amip/atmosphere/boundary_conditions/global.N96/2021.07.08/amip_sst_n96_greg.pp
  hashes:
    binhash: c0268c388a150ceea10adbaa74c82fdc
    md5: 47368fc3565d554200b0f1fe78e79416
work/atmosphere/INPUT/biogenic_351sm.N96L38:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/biogenic_351sm.N96L38
  hashes:
    binhash: 35f8585c3290dfc25ed19e7d93f6a1bb
    md5: 55eb75f602a4639fb3c8ff40e36eb661
work/atmosphere/INPUT/cable_vegfunc_N96.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/land/vegetation/global.N96/2025.08.29/cable_vegfunc_N96.anc
  hashes:
    binhash: a3264254e656d49eabb828adb861c93f
    md5: d36f7104db31c372fbbf1cdc90a4e4f4
work/atmosphere/INPUT/modis_phenology_csiro_13evergreen.txt:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2025.08.29/modis_phenology_csiro_13evergreen.txt
  hashes:
    binhash: 301907643ca1dfecfdcecd5f65dfd5e6
    md5: c8f344d7371949fb6aac7f71e1e003d6
work/atmosphere/INPUT/ozone_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/forcing/global.N96/2026.03.03/ozone_1849_2023_cmip7.anc
  hashes:
    binhash: 836ab6769fe6d7109edcfa111b41493f
    md5: 9acc7eacb5d77eba93a0751113db4e32
work/atmosphere/INPUT/pftlookup_cable3_Pfix.csv:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2026.02.10/pftlookup_cable3_Pfix.csv
  hashes:
    binhash: fe0c4ad208586a2ccf2cb113919a8332
    md5: d9a4d71ee8038029739c23a1b829ab6a
work/atmosphere/INPUT/scycl_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/aerosol/global.N96/2026.01.06/scycl_1849_2023_cmip7.anc
  hashes:
    binhash: 532153e267ee06b4a6c93e10500ffd46
    md5: 9ed52e5de4e55f10baeec1b35c75d1a8
work/atmosphere/INPUT/spec3a_lw_hadgem1_6on:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_lw_hadgem1_6on
  hashes:
    binhash: 278569974348c9583fe0a2a9e1828ffd
    md5: 9ff85916dbb36ba6679b954d16387aee
work/atmosphere/INPUT/spec3a_sw_hadgem1_6on:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_sw_hadgem1_6on
  hashes:
    binhash: 149899ecc54ed754ab8c6f05cb99f140
    md5: 0e74c13cf3333132f38d8c5c52e1c7eb
work/atmosphere/INPUT/stasets/X01001218:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01001218
  hashes:
    binhash: 31ad5018def8692ff4fd1c147251717d
    md5: 7293caa27798d235bd5520eede9700fb
work/atmosphere/INPUT/stasets/X01002207:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01002207
  hashes:
    binhash: 5a15975e876b56375fd56d4058c31ddc
    md5: 448daeebba685950d0c347d0493b5fc4
work/atmosphere/INPUT/stasets/X01003236:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003236
  hashes:
    binhash: 15113460723c9cbb80d47fd816f9fe7f
    md5: 71a2288ee0a7d0fc89dafe95653c128a
work/atmosphere/INPUT/stasets/X01003237:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003237
  hashes:
    binhash: e90b9e7718ba31b7318f9b10820b8d10
    md5: 4efd39ac9a917525bbc35146d6770e3b
work/atmosphere/INPUT/stasets/X01003254:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003254
  hashes:
    binhash: a118be515a8e248fd7f671dded21768b
    md5: 1b5f7755f752c2ee2086ac6eba886ca3
work/atmosphere/INPUT/stasets/X01003255:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003255
  hashes:
    binhash: 123cd6ecc51b1ab879ba0b463695b0a8
    md5: f23a78b048f0cb52ed0e2beb57f00fa8
work/atmosphere/INPUT/stasets/X01003274:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003274
  hashes:
    binhash: 74c2f9ab3626013fa887be54621ff2f6
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003275:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003275
  hashes:
    binhash: 3ce8c2a5e46c4acdc8c5dda83806b81e
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003276:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003276
  hashes:
    binhash: d4e27033f83091ab5828d12b38cafd49
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003277:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003277
  hashes:
    binhash: f3c7ee4d380b4945fdfdfa7fb1be6170
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003278:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003278
  hashes:
    binhash: 234f48372415f86d7fcf1ee48e92bd43
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003279:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003279
  hashes:
    binhash: cd4742ce8f909c30aa079873a3dcb544
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003280:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003280
  hashes:
    binhash: 5b94b44b27c245d032a7f4d6f39def9f
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003281:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003281
  hashes:
    binhash: 5ccbe8c93e97f377c381f2892267c0bc
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003286:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003286
  hashes:
    binhash: b3a5d3577f1e64fe502d4cb55a3495fe
    md5: 062ab130605e4771a89b2a300a6154bf
work/atmosphere/INPUT/stasets/X01005207:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01005207
  hashes:
    binhash: 23abda824c98f9ccb3107ea0528a89c0
    md5: 3d1ccb47257c379b909e8d6098ab95a0
work/atmosphere/INPUT/stasets/X01005208:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01005208
  hashes:
    binhash: 9e7c792aa9aa34e871a09a0f31344bbb
    md5: 8685052394200b839f115a667e7890ff
work/atmosphere/INPUT/stasets/X01005222:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01005222
  hashes:
    binhash: 8ff456c8104c3d8080375c3dc288edb9
    md5: 3edd8e46166dbed4102c329991a7a497
work/atmosphere/INPUT/stasets/X01005223:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01005223
  hashes:
    binhash: 4055c7d1461e9c586f4bd75c384c2b56
    md5: 4633fea316272fd71cd823881d100c14
work/atmosphere/INPUT/stasets/X01010206:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01010206
  hashes:
    binhash: 0f0fe82f1108c9d3da2c9c03ed3b6e30
    md5: 7d5e82e70a2f3936743eb957462d41aa
work/atmosphere/INPUT/sulpc_oxidants_N96_L38:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/sulpc_oxidants_N96_L38
  hashes:
    binhash: e8b31e6ca1af7da756d87243e622e3c8
    md5: 7c42d1faf74b2b9f6819f2349a8d0d25
work/atmosphere/INPUT/volcts_cmip7.dat:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/forcing/resolution_independent/2025.12.01/volcts_cmip7.dat
  hashes:
    binhash: 0a36e587f17b1b9bef4b3bbe9d4731dc
    md5: 89a3d931712da3805369894e068280b3
