format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/atmosphere/restart_dump.astart
  hashes:
    binhash: 7f22b38944f92d2cabe3982c3b381c30
    md5: 2af17d4b4a8ab7674cffbca14b4b9944
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/atmosphere/um.res.yaml
  hashes:
    binhash: 1cb41d2f6c88bcb0af03c7e9712e9683
    md5: 50196dc2f03f5466e4fa058caad61cd9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/coupler/a2i.nc
  hashes:
    binhash: 5e4fabb0f14b01221ced158c37cdda0a
    md5: 631092fab515d0304fb881b3abd8d575
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/coupler/i2a.nc
  hashes:
    binhash: 0b22f703648c50c2937d018224c541fc
    md5: 4e2bdc7e42b7f254d5142d1dfe8552ba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/coupler/o2i.nc
  hashes:
    binhash: 11d620a239439084a514b111acfbfd69
    md5: 23b13d12c680080228e12938db6532d3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ice/cice_in.nml
  hashes:
    binhash: 2a10d5ca226be2394fdbae0e8571e855
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ice/ice.restart_file
  hashes:
    binhash: a10429c4dc6906c97578d8a6ea570573
    md5: d04f53e25a6c9756a81e455a16030925
work/ice/RESTART/iced.2080-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ice/iced.2080-01-01-00000.nc
  hashes:
    binhash: 1c4ab1dccf372a3c203f89bb2e95633e
    md5: e12555a648825f304f8a863a10b1ff2b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ice/mice.nc
  hashes:
    binhash: ae8c91012bedcbd73711c289a30645c9
    md5: c236fc62f414bceeb49157cd2e26f358
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_age.res.nc
  hashes:
    binhash: 6d6afc4c67b91f2cf0b8c7766d16e82b
    md5: eb66a26eba27b1be85e5c4e8ab3ff7bd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2720ededc22194e610702590b870e3be
    md5: da589243e8c6e25eead3d5c1f2330a0b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 00fc7ec6626b815d3b0c9467e8bca674
    md5: 52aa71a0a38c6d2be5ab554eb0688ebd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_density.res.nc
  hashes:
    binhash: 3f521dcf161a225a030f449a128ff17f
    md5: f00ee346f90bfa5ef15ac0e78561cde3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 20a3495d6cc3874ce0158137a52f9bd9
    md5: 19c3a5123fe9020d951b365d8a9519b4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c945b75c11a120d846449f1abfc34e65
    md5: 346ab3c653fe75e20e1b4410376802de
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 50a205ac59fddcb86d563935f1235b7c
    md5: 5c44f2be76912a0566172692146c79b9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3a78dc8b63cbc067b5f38365c28ef6d7
    md5: 5876de7d22df20cd5faefdb24339c820
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bcbd4b44e13ccffd9383132f66fc3d2a
    md5: 043f53489e9b5c9e0239c06f70fa5feb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1e8f3922dd038383b3f089c79248c018
    md5: 13cedb1ccde6b993fbd12afc326975f1
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_solo.res
  hashes:
    binhash: b8fa8b0494222c2afc4ac37ecd06f9a3
    md5: 84297815ec573abf65c2708b4cded5f6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1d4dd157e1d8958b3dae599fa69cd01e
    md5: 84bce5e02f80ab59d4288e6dc6be67df
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ea9fb1db6c0f438035f4a2fcc664dc0c
    md5: 4f6af8baf76b2e560b6d1b2e6edfc54b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_tracer.res
  hashes:
    binhash: 0efbb7e35946696d29dc43de8c30ef2b
    md5: 185af9ac1ce6c8a9230efe70da1cee49
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b257bed358baa4ef55751a01ff893aed
    md5: 8c23e66f1a5f78b2c930f633a70f7cec
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 00a4875c7cbb7524a5b35f96be46cfbd
    md5: 49a7e9253bf591ea2953c7bb8ce15f9b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f41c914a984c19e9bbf7cdb69c1a08aa
    md5: 42216a75b6da5aa847596491dd741306
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-scen7-h-esm-scen7-h-1.0-r2i1p1f1-67e34141/restart057/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 01e672305e147d5db4990af478c2fe97
    md5: fac403654fc1d7b9c75b699855a993a8
